// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
//

/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
"momina " 
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;

    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIKzg6eTBGuF1fVaXWQ41B7D-tTaPpVxc',
    appId: '1:463190577162:web:8fd389ec798f4ed0cf4ff3',
    messagingSenderId: '463190577162',
    projectId: 'services-app-ef22f',
    authDomain: 'services-app-ef22f.firebaseapp.com',
    storageBucket: 'services-app-ef22f.firebasestorage.app',
    measurementId: 'G-V9ZRGQ65P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADRkDMosFwzlC4bS7Qxuk6aTqkNlALJZ4',
    appId: '1:463190577162:android:f09c52c9b9642781cf4ff3',
    messagingSenderId: '463190577162',
    projectId: 'services-app-ef22f',
    storageBucket: 'services-app-ef22f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfIdyaX8NFk4c0wywXh9o3GMzM0l58HBQ',
    appId: '1:463190577162:ios:f576e9c802cdae93cf4ff3',
    messagingSenderId: '463190577162',
    projectId: 'services-app-ef22f',
    storageBucket: 'services-app-ef22f.firebasestorage.app',
    iosBundleId: 'com.example.serviceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfIdyaX8NFk4c0wywXh9o3GMzM0l58HBQ',
    appId: '1:463190577162:ios:f576e9c802cdae93cf4ff3',
    messagingSenderId: '463190577162',
    projectId: 'services-app-ef22f',
    storageBucket: 'services-app-ef22f.firebasestorage.app',
    iosBundleId: 'com.example.serviceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIKzg6eTBGuF1fVaXWQ41B7D-tTaPpVxc',
    appId: '1:463190577162:web:4b067a8bb09bf5bfcf4ff3',
    messagingSenderId: '463190577162',
    projectId: 'services-app-ef22f',
    authDomain: 'services-app-ef22f.firebaseapp.com',
    storageBucket: 'services-app-ef22f.firebasestorage.app',
    measurementId: 'G-EZGPNBT3RD',
  );
}
